name: Documentation Change Request
description: Suggest changes or improvements to the documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!
  
  - type: dropdown
    id: type
    attributes:
      label: Type of Documentation Change
      options:
        - Error/Typo fix
        - Content update
        - New documentation
        - Translation
        - Reorganization
        - Other
    validations:
      required: true
  
  - type: input
    id: page
    attributes:
      label: Documentation Page URL or Path
      description: Please provide the URL or file path of the documentation page you're referring to.
      placeholder: e.g., https://docs.dify.ai/getting-started or /getting-started.md
    validations:
      required: false
  
  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the documentation currently say?
      placeholder: Paste the current content here...
    validations:
      required: false
  
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: What would you like to be changed or added?
      placeholder: Describe your suggested changes...
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why do you think this change would improve the documentation?
      placeholder: Explain why this change would be helpful...
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contribution guidelines
      options:
        - label: I agree to follow Dify's documentation [contribution guidelines](https://github.com/langgenius/dify/blob/0277a37fcad5ad86aeb239485c27fffd5cd90043/CONTRIBUTING.md)
          required: true
        - label: I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
          required: true
        - label: I confirm that I am using English to submit this report, otherwise it will be closed.
          required: true
        - label: 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
          required: true
        - label: "Please do not modify this template :) and fill in all the required fields."
          required: true